### ISSUE TITLE
헤시안 관련해서 질문드립니다.

### ISSUE THREAD

**Issue by Yoontae6719** [xxxnell/how-do-vits-work#11]
안녕하세요, 해당 논문 매우 재밌게 잘 읽었습니다.

관련해서, Hassian max eegenvalues spectra를 논문처럼 구현해보고 싶은데 혹시 이와 관련된 코드는 어디에서 확인 할 수 있을까요?

미리 답변 감사드립니다!

**Comment by xxxnell** [comment]
Hi @Yoontae6719

Thank you for your support! Unfortunately, the code for the Hessian eigenvalue spectra is messy at this moment, so I did not release it yet. Please send me an email (namuk.park _at_ yonsei.ac.kr) or leave your email address here. Then I'll give you more information.

**Comment by xxxnell** [comment]
Please check your @unist.ac.kr mailbox!

**Comment by johnjaejunlee95** [comment]
Hi Namuk,
Can I also get the Hessian eigenvalue spectra code, if possible?
