### ISSUE TITLE
How to plot the Trajectories in polar coordinates?

### ISSUE THREAD

**Issue by xin-fight** [xxxnell/how-do-vits-work#13]
Hello author, your work has brought me a lot, but when I read the paper, I am very interested in the drawing process of Figure 1(b)[Trajectories in polar coordinates]. Can you open source it?
Best regards to you

**Comment by xxxnell** [comment]
Hi @xin-fight, thank you for the kind words.
During the conference period, I found a potential risk of misleading readers and a reproducibility issue in the trajectory experiment. Please ignore the trajectory experiment to minimize misleading. The camera-ready manuscript will fix this. Sorry for the confusion.
