### ISSUE TITLE
Running time for visualizing the loss landscape

### ISSUE THREAD

**Issue by waitingcheung** [xxxnell/how-do-vits-work#16]
Thank you for the amazing work! The summary organizes the main points of the paper really well and helps facilitate future research.

I would like to visualize the loss landscape for my model and I am trying the Python notebook in this repository on Colab. Apparently it is a long process and I would like to have a rough estimation on the time it will take for my model.

Could you kindly advise how long it took for you to run the notebook on Colab or on your machine?

**Comment by xxxnell** [comment]
Hi, @waitingcheung . Thank you for your support. The loss landscape visualization evaluates the model on a grid with 441(=21×21) points by default. So, the running time for the code to investigate the loss is equal to the time for training the model for 441 epochs. This can take tens of hours to days.
