### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by 123456789-qwer** [xxxnell/how-do-vits-work#18]
https://user-images.githubusercontent.com/930317/158025258-e9a5a454-99de-4d22-bc93-b217cdf06abb.jpeg
Where can I find other pictures?

**Comment by xxxnell** [comment]
Hi @123456789-qwer! The file name of this image is `ILSVRC2012_val_00046145` and it is from [the kit fox class](https://knowyourdata-tfds.withgoogle.com/#dataset=imagenet2012&filters=default_segment.imagenet2012.label.value:%5Bkit%20fox%2C%20Vulpes%20macrotis%5D(http%3A%2F%2Fwordnet-rdf.princeton.edu%2Fwn30%2F02119789-n),default_segment.imagenet2012.split.value:validation&tab=ITEM&select=default_segment.imagenet2012.label.value&draw=default_segment.imagenet2012.split.value,,&item=ILSVRC2012_val_00046145.JPEG&expanded_groups=imagenet2012) of the [ImageNet](https://www.image-net.org/index.php) validation dataset. I found this image at [MAE](https://colab.research.google.com/github/facebookresearch/mae/blob/main/demo/mae_visualize.ipynb). If you want to get more rigorous results in the Fourier analysis experiment, I recommend repeating the experiment on multiple images (eg from the ImageNet validation dataset) and averaging the results. Or you can simply borrow some example images from [knowyourdata](https://knowyourdata-tfds.withgoogle.com/#dataset=imagenet2012&filters=default_segment.imagenet2012.split.value:validation&tab=STATS&select=default_segment.imagenet2012.label.value&draw=default_segment.imagenet2012.split.value,,&expanded_groups=kyd,imagenet2012), e.g.,

```python
xs = [
    "https://user-images.githubusercontent.com/930317/158025258-e9a5a454-99de-4d22-bc93-b217cdf06abb.jpeg",
    "https://knowyourdata-tfds.withgoogle.com/serve_image?&id=ILSVRC2012_val_00042330.JPEG&dataset=imagenet2012",
    "https://knowyourdata-tfds.withgoogle.com/serve_image?&id=ILSVRC2012_val_00020406.JPEG&dataset=imagenet2012",
]
```


To prepare the ImageNet dataset, you can refer to the following docs for example: ["Download, pre-process, and upload the ImageNet dataset"](https://cloud.google.com/tpu/docs/imagenet-setup) and ["Preparation of ImageNet (ILSVRC2012)"](https://gist.github.com/antoinebrl/7d00d5cb6c95ef194c737392ef7e476a). Please feel free to leave a comment if you have any problems.
