### ISSUE TITLE
Support of the hessian max eigenvalue spectrum code

### ISSUE THREAD

**Issue by big-chan** [xxxnell/how-do-vits-work#2]
Hello.
Thanks for contributing to this project.

Could u share the hessian max eigenvalue spectrum code?
Thank you

**Comment by xxxnell** [comment]
Hi Dae Chan,

I replied to your email. Please check your mailbox. 

Thank you for your support!

**Comment by JHLEE17** [comment]
Hi Namuk. 

I read your paper very impressively.
Could you share the code for me too?
My e-mail address is  jhlees17@naver.com  

Thank you.

**Comment by sjtuytc** [comment]
Hi Namuk @xxxnell , thanks for your great paper.
Could you share the code with me as well?
My email is zelin@link.cuhk.edu.hk
Yours,
Zelin Zhao

**Comment by jibm819** [comment]
Hello Namuk.
Your work was very impressive
and I want to study more about model analysis with hessign max eigenvalue spectrums.
Could you share the code please?
My email is jibm819@gmail.com
Thank you.

**Comment by HashmatShadab** [comment]
Hi Namuk 

Could you share the code with me as well?
My email is [hashmat.malik@mbzuai.ac.ae](mailto:hashmat.malik@mbzuai.ac.ae)
Regards,
Hashmat Shadab
