### ISSUE TITLE
Hi，something about object detection...

### ISSUE THREAD

**Issue by ross-Hr** [xxxnell/how-do-vits-work#20]
Hi,
  I am ross. 
  Excellent work !!!
  The experiments are basically classification problems.

   Does the analysis result change much if the task switch to the object detection?

**Comment by xxxnell** [comment]
Hi ross, thank you for the question. As mentioned in Discussion section, we believe that self-attention can significantly improve the results in dense prediction tasks and that the key results remain the same. But we leave a detailed investigation for future work. In fact, I am contemplating whether to analyze the characteristics of ViT in dense prediction tasks as a follow-up work. Anyway, thank you for the kind words!
