### ISSUE TITLE
ViT vs ResNet: Did you use SAM optimizer?

### ISSUE THREAD

**Issue by quannguyen268** [xxxnell/how-do-vits-work#28]
In section 1.1 Related works, I see that you have a comparision between loss landscape of ResNet and ViT. Did you use SAM optimizer while training both models at this stage of comparing or not ?
![image](https://user-images.githubusercontent.com/79714533/204486946-4fc9f002-63ee-40cf-ac1e-6facfbcdd4bc.png)

**Comment by xxxnell** [comment]
Hi @quannguyen268, thank you for reaching out. 

We do not use SAM optimizer for our experiments.
