### ISSUE TITLE
Total parameters in AlterNet

### ISSUE THREAD

**Issue by sauravtii** [xxxnell/how-do-vits-work#33]
What are the total number of parameters and total FLOPS of AlterNet for CIFAR-100 and ImageNet dataset?

**Comment by xxxnell** [comment]
Hi @sauravtii, thank you for reaching out.

The number of params and MACs (~ 0.5 × FLOPs) of AlterNet-50 are 33.0M and 1.52G on CIFAR-100, respectively. On ImageNet, they are 34.9M and 4.75G . For comparison, the FLOPs and MACs of (modified) ResNet-50 as a baseline are 28.2M and 1.38G on CIFAR-100, and 30.0M and 4.35G on ImageNet. 

The MACs have been calculated using [`thop`](https://github.com/Lyken17/pytorch-OpCounter) library.
