### ISSUE TITLE
Hessian Max eigenvalue spectra 코드 관련 질문드립니다.

### ISSUE THREAD

**Issue by Levinna** [xxxnell/how-do-vits-work#34]
안녕하세요, 
논문을 통해서 Neural Network Visualization에 관심을 갖게 되었습니다. 좋은 논문 써 주셔서 감사합니다. 

Github에 다른 Visualization 관련 Tutorial이 잘 제공되어 확인할 수 있었는데 Hessian Max eigenvalue 관련 코드의 경우 따로 메일을 남기면 관련 자료를 보내주시는 것 같아 이슈를 남기게 되었습니다. 혹시 아래 메일로 관련 내용을 보내주실 수 있을까요?

제 메일 주소는 khna@handong.ac.kr 입니다. 감사합니다.

**Comment by xxxnell** [comment]
Hi @Levinna,

Thank you for your support. I have sent a guideline to implement the Hessian max eigenvalue spectrum. You may also find some information at the [issue #12](https://github.com/xxxnell/how-do-vits-work/issues/12#issuecomment-1113991017).
