### ISSUE TITLE
Lesion study

### ISSUE THREAD

**Issue by liguopeng0923** [xxxnell/how-do-vits-work#41]
Hi @xxxnell ,

I find it hard to understand the conclusions about the lesion study. For example, VIT has not satisfied your conclusion (i.e., the latter MSA is more important)
<img width="796" alt="image" src="https://github.com/xxxnell/how-do-vits-work/assets/61257834/b3a0eb13-6ec6-480e-9ab4-809b76f08092">

**Comment by xxxnell** [comment]
Hi @liguopeng0923 ,

Thank you for the great question. Indeed, when we discuss *shallow* Vision Transformers or even Swin Transformers, which are serial connections of shallow Transformers, the statement -- that the latter self-attentions are more important -- holds precisely. Nonetheless, for *deep* Vision Transformers, the middle self-attention layers take on a prominent role in determining accuracy, thus outshining the latter self-attention layers.

This occurrence can be linked to a phenomenon known as *attention collapse*. Here, the latter self-attention maps constrict into specific patterns that are not significantly influenced by the query token. Consequently, the latter several self-attention layers tends to lose their importance, particularly in classification tasks. Essentially, this observation infers that Vision Transformers can encounter the scaling problem with respect to their depth. [DeepViT](https://arxiv.org/abs/2103.11886) also tried to address this issue.

Happy holidays!
