### ISSUE TITLE
Can I get a guideline for hessian eigenvalue visualization?

### ISSUE THREAD

**Issue by gihyunkim** [xxxnell/how-do-vits-work#42]
Hi, I am Ph.D/M.S. integrated student at Yonsei University. I am very interested in your research and I am looking into your code. However, I couldn't find the code about hessian eigenvalue and recognized that you don't share it right now. 

It would be very pleasure if you give me the code or guideline to write about hessian eigenvalue visualization.

my email: kkh9314@yonsei.ac.kr

Thank you.

**Comment by xxxnell** [comment]
Hi @gihyunkim,

Thank you for reaching out. I've just sent the pseudocode for implementing the Hessian eigenvalue spectrum. Alternatively, you can also check out [Issue #12](https://github.com/xxxnell/how-do-vits-work/issues/12).
